dist: trusty
notifications:
  slack: ventureum-team:DSE8wxmLTenq0Yz17BrYBWg9
language: node_js
node_js:
- 8
fail_fast: true
script:
- npm run eslint
- npm run flow
- unzip src/tests/__snapshots__
- npm test
- npm run build:staging
- mv ./build ./build_staging
- npm run build:prod
- mv ./build ./build_prod
deploy:
  - provider: s3
    skip_cleanup: true
    cache_control: "max-age=0,no-cache,no-store,must-revalidate"
    access_key_id: $S3_ACCESS_KEY
    secret_access_key: $S3_SECRET
    bucket: testnet.chainsfr.com
    local_dir: build_staging
    region: us-east-1
    acl: public_read
    on:
        branch: master
  - provider: s3
    skip_cleanup: true
    cache_control: "max-age=0,no-cache,no-store,must-revalidate"
    access_key_id: $S3_ACCESS_KEY
    secret_access_key: $S3_SECRET
    bucket: app.chainsfr.com
    local_dir: build_prod
    region: us-east-1
    acl: public_read
    on:
        branch: master
true:
  branch: master
